### ISSUE TITLE
How to configure it?

### ISSUE THREAD

**Issue by berwynhoyt** [guysv/ilua#31]
ilua looks very powerful, but there do not appear to be any instructions or a README on how to configure it, for example:

- prompt content
- colors
- whether it should confirm on exit

I tried `ilua -h` but it doesn't answer these questions.

Am I missing something?

**Comment by guysv** [comment]
this project is kinda old but essentially all `ilua` does is running a jupyter console frontend with a the new lua kernel.

If you are seeking to customize the console, i'd suggest reading [jupyter console docs](https://jupyter-console.readthedocs.io/en/latest/) and maybe something there is relevant.

**Comment by berwynhoyt** [comment]
Thanks.
