### ISSUE TITLE
Passing ipython command line arguments

### ISSUE THREAD

**Issue by hroncok** [guysv/ilua#9]
Is there a way to start `ilua` with some arguments, such as `ilua --no-confirm-exit --no-banner`?

**Comment by guysv** [comment]
Looks like this requires a trivial patch in [consoleapp.py](https://github.com/guysv/ilua/blob/master/ilua/) that will forward excess arguments to the jupyter frontend.

I'll see what I can do.

**Comment by guysv** [comment]
ooh, by the way, you can fire up ilua via jupyter-console's entry point `jupyter console --kernel=ilua`. That way you'll also get access to ipython's tweaking options.

https://jupyter-console.readthedocs.io/en/latest/

**Comment by hroncok** [comment]
I get `jupyter_client.kernelspec.NoSuchKernel: No such kernel named ilua`.

With `lua` I get it working, but I cannot specify my custom interpreter :(

**Comment by guysv** [comment]
Hmm, I kinda hoped you could. but I couldn't remember exactly :(

**Comment by guysv** [comment]
Wait, ILua also takes parameters from environment variables.
`ILUA_INTERPRETER=mylua ilua` equals `ilua -i mylua`

**Comment by hroncok** [comment]
```
ILUA_INTERPRETER=mylua jupyter console --kernel=lua --no-confirm-exit
```

Get's the job done. `--no-banner` is not recognized by `jupyter console`, but I can live with that. Thnaks.

**Comment by hroncok** [comment]
Oh, sorry. It doesn't really use `mylua`.

**Comment by hroncok** [comment]
Neither does `LUA_INTERPRETER` works, as mentioned in:

https://github.com/guysv/ilua/blob/93fea36c3340b530e80b70bfc30957ce1d7e7798/ilua/app.py#L17-L21

Maybe because this code is not used when `jupyter console --kernel=lua` starts?

**Comment by guysv** [comment]
hmm, it should be used, according to kernel.json
https://github.com/guysv/ilua/blob/master/defaultspec/kernel.json

I misled you, the correct variable is `ILUA_LUA_INTERPRETER`
I should've documented that >_<

**Comment by hroncok** [comment]
```
$ ILUA_LUA_INTERPRETER=mylua jupyter console --kernel=lua --no-confirm-exit
```

\o/

Thanks.

**Comment by guysv** [comment]
Aight, looks like a good workaround. I'll close this for now.
